package KieRule
import process.engine.component.RestIntCall;
import process.engine.component.RuleHelper;
import process.engine.vo.DataForm;
import process.engine.vo.DataMain;
import process.engine.vo.DataWith;
import process.engine.vo.VoCommitTask;
import process.engine.vo.VoNewProcInsWithPar
import java.util.HashMap
import java.util.Map
import java.lang.String
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.time.LocalDateTime
import java.util.List;


//精准发电自动创建工单
rule "PRECISE_POWER_AUTO_CREATE1"
    when
        $vo: VoCommitTask($insNodeId : insNodeId);
        $helper : RuleHelper();
    then
        $helper.info("----->BBBBBBBBB insNodeId: {}#,  PRECISE_POWER_AUTO_CREATE1", $insNodeId);
        VoNewProcInsWithPar withPar=$helper.getVoNewProcInsWithPar($insNodeId);
        Map<String,String> map2 = null;
        if (withPar != null ) {
            map2 = withPar.getData_transform();
        }
        // 人工发起
        String decision = null;
        String assignGroupId = null;
        if (withPar == null ||map2 == null || map2.isEmpty() ||
            (map2.get("isAuto") != null && map2.get("isAuto").length()>0)) {
            decision = "4";// 流转到【人工派发】节点
        } else { // 自动发起
            // 判断能否取到【县级发电审核】的大角色
            // 取到则继续流转；如果取不则，流转到【取地市审核角色】节点
            String roleId=null;
            RestIntCall call = $helper.getRestIntCall();
            List<Map<String, String>> response;
            String api = "/api/process-engine/query_after_in_condition_2?proc_id=82&node_id=19";// 19：查询【取发电审核角色】节点以后节点的大角色列表
            response = call.call_2(1, "engine-inf", api, null, null);
            $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: response.size(): {}# ", response == null ? 0 : response.size());
            for(Map<String,String> obj: response) {
                $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: obj.id: {}# ", obj.get("id"));
                $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: obj.name: {}# ", obj.get("name"));
                $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: obj.groupId: {}# ", obj.get("groupId"));
                $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: obj.userId: {}# ", obj.get("userId"));
                if (obj.get("id").equals("15")) {// 判断是否拥有【县级发电审核】的大角色
                    roleId = (String) obj.get("groupId");
                }
            }
            $helper.info("-----------> PRECISE_POWER_AUTO_CREATE1: roleId: {}# ", roleId);
            if(roleId == null){
                decision = "6";// 流转到【取地市审核角色】自动节点
            } else {
                String userId ="运维建单人";
                String deptId ="中国移动通信集团甘肃有限公司";
                String role ="建单人";
                map2.put("sendUserid", "ywjdr");
                map2.put("operationUser", userId);
                map2.put("department", deptId);
                map2.put("role", role);
                map2.put("telephone", "");
                map2.put("status","1");
                String operateTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                map2.put("operateTime", operateTime);
                $helper.putFormData($insNodeId, map2);
                $helper.info("----->EEEEEEEEEE insNodeId: {}#,  PRECISE_POWER_AUTO_CREATE1", $insNodeId);
                decision = "2";// 流转到【取发电审核角色】自动节点
            }
        }

        $vo.setDecision(decision);
        $vo.setRuleFlag(1);
end;
